services:
  - type: web
    name: codeleap-api
    runtime: python
    rootDir: api
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python manage.py migrate
    startCommand: gunicorn server.wsgi --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: codeleap-db
          property: connectionString
      - key: FRONTEND_ORIGIN
        value: https://codeleap-frontend.onrender.com
  - type: web
    name: codeleap-frontend
    runtime: static
    rootDir: client
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://codeleap-api.onrender.com/careers/

databases:
  - name: codeleap-db
